image: hashicorp/terraform:latest

pipelines:
  custom:
    dev:
      - step:
          name: Plan and apply Terragrunt files (dev)
          script:
            - cd tf/dev
            - terragrunt plan
            - terragrunt apply
          trigger:
            - message: 'Apply dev'
      - step:
          name: Run installation and configuration scripts
          script:
            - cd terraform/scripts
            - chmod +x install_websphere.sh configure_websphere.sh
            - if [ "$BITBUCKET_BRANCH" = "dev" ]; then ./install_websphere.sh && ./configure_websphere.sh ; fi
    int:
      - step:
          name: Plan and apply Terragrunt files (int)
          script:
            - cd tf/int
            - terragrunt plan
            - terragrunt apply
          trigger:
            - merge_request:
                source: 'feature'
                destination: 'develop'
      - step:
          name: Run installation and configuration scripts
          script:
            - cd terraform/scripts
            - chmod +x install_websphere.sh configure_websphere.sh
            - if [ "$BITBUCKET_BRANCH" = "int" ]; then ./install_websphere.sh && ./configure_websphere.sh ; fi
    prod:
      - step:
          name: Plan and apply Terragrunt files (prod)
          script:
            - cd tf/prod
            - terragrunt plan
            - terragrunt apply
          trigger:
                  - merge_request:
                      source: 'develop'
                      destination: 'main'
            - step:
                name: Run installation and configuration scripts
                script:
                  - cd terraform/scripts
                  - chmod +x install_websphere.sh configure_websphere.sh
                  - if [ "$BITBUCKET_BRANCH" = "prod" ]; then ./install_websphere.sh && ./configure_websphere.sh ; fi
